import { useCallback, useEffect, useState } from "react";
import { Box, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import { createCompany, createSubscriptionPayment, getCompanies, updateCompany } from "../../api/platform";

const today=()=>new Date().toISOString().slice(0,10);
const money=v=>`${new Intl.NumberFormat("uz-UZ").format(Number(v||0))} so'm`;
const date=v=>v?new Date(v).toLocaleDateString("uz-UZ"):"-";
const emptyCompany={name:"",slug:"",phone:"",subscription_ends_at:"",first_name:"",last_name:"",username:"",password:"",admin_phone:""};

const PlatformDashboard=()=>{
  const navigate=useNavigate(); const [companies,setCompanies]=useState([]); const [loading,setLoading]=useState(true); const [dialog,setDialog]=useState(""); const [form,setForm]=useState({}); const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{if(!localStorage.getItem("platform_token")){navigate("/platform/login",{replace:true});return;}setLoading(true);try{setCompanies((await getCompanies()).data.companies||[]);}catch(e){if(e?.response?.status===401){localStorage.removeItem("platform_token");navigate("/platform/login",{replace:true});}else toast.error(e?.response?.data?.message||"Korxonalarni olishda xato.");}finally{setLoading(false);}},[navigate]);
  useEffect(()=>{load();},[load]);
  const save=async()=>{setSaving(true);try{if(dialog==="company")await createCompany({name:form.name,slug:form.slug,phone:form.phone||null,subscription_ends_at:form.subscription_ends_at||null,super_admin:{first_name:form.first_name,last_name:form.last_name,username:form.username,password:form.password,phone:form.admin_phone||null}});if(dialog==="payment")await createSubscriptionPayment({company_id:form.company_id,amount:Number(form.amount),paid_at:form.paid_at,period_from:form.period_from||null,period_to:form.period_to||null,note:form.note||null});toast.success("Saqlandi.");setDialog("");await load();}catch(e){toast.error(e?.response?.data?.message||"Saqlashda xato.");}finally{setSaving(false);}};
  const toggle=async company=>{const status=company.status==="active"?"suspended":"active";try{await updateCompany(company.id,{status,subscription_status:status==="active"?"active":"suspended"});await load();}catch(e){toast.error(e?.response?.data?.message||"Holatni o'zgartirishda xato.");}};
  const logout=()=>{localStorage.removeItem("platform_token");localStorage.removeItem("platform_admin");navigate("/platform/login");};
  return <Box className="min-h-screen bg-slate-100 p-4 md:p-7"><Box className="mx-auto max-w-7xl"><Box className="mb-5 flex flex-wrap items-end justify-between gap-3"><Box><Typography variant="h5" fontWeight={900}>Korxonalar boshqaruvi</Typography><Typography color="text.secondary">CRM mijozlari va oylik obunalar</Typography></Box><Box className="flex gap-2"><Button variant="outlined" onClick={logout}>Chiqish</Button><Button variant="contained" onClick={()=>{setForm(emptyCompany);setDialog("company")}}>Korxona qo'shish</Button></Box></Box>{loading?<Box className="flex min-h-64 items-center justify-center"><CircularProgress/></Box>:<Paper elevation={0} className="overflow-auto border border-slate-200" sx={{borderRadius:2}}><Table><TableHead><TableRow><TableCell>Korxona</TableCell><TableCell>Kod</TableCell><TableCell>Foydalanuvchilar</TableCell><TableCell>Obuna muddati</TableCell><TableCell>Jami to'lov</TableCell><TableCell>Holati</TableCell><TableCell align="right">Amallar</TableCell></TableRow></TableHead><TableBody>{companies.map(c=><TableRow key={c.id} hover><TableCell><Typography fontWeight={800}>{c.name}</Typography><Typography variant="body2" color="text.secondary">{c.phone||"-"}</Typography></TableCell><TableCell>{c.slug}</TableCell><TableCell>{c.users_count}</TableCell><TableCell>{date(c.ends_at)}</TableCell><TableCell>{money(c.total_paid)}</TableCell><TableCell><Chip size="small" label={c.status==="active"?"Faol":"To'xtatilgan"} color={c.status==="active"?"success":"error"}/></TableCell><TableCell align="right"><Button size="small" onClick={()=>{setForm({company_id:c.id,amount:"",paid_at:today(),period_from:"",period_to:"",note:""});setDialog("payment")}}>To'lov</Button><Button size="small" color={c.status==="active"?"error":"success"} onClick={()=>toggle(c)}>{c.status==="active"?"To'xtatish":"Faollashtirish"}</Button></TableCell></TableRow>)}</TableBody></Table></Paper>}</Box><Entry dialog={dialog} form={form} setForm={setForm} close={()=>setDialog("")} save={save} saving={saving}/></Box>;
};
const Entry=({dialog,form,setForm,close,save,saving})=>{if(!dialog)return null;const f=(k,l,t="text")=><TextField type={t} label={l} value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})} slotProps={t==="date"?{inputLabel:{shrink:true}}:undefined}/>;return <Dialog open fullWidth maxWidth="sm" onClose={close}><DialogTitle fontWeight={900}>{dialog==="company"?"Yangi korxona":"Obuna to'lovi"}</DialogTitle><DialogContent><Box className="mt-2 grid gap-3">{dialog==="company"?<>{f("name","Korxona nomi")}{f("slug","Korxona kodi")}{f("phone","Korxona telefoni")}{f("subscription_ends_at","Obuna tugash sanasi","date")}<Typography fontWeight={800} className="pt-2">Super administrator</Typography>{f("first_name","Ism")}{f("last_name","Familiya")}{f("username","Username")}{f("password","Parol","password")}{f("admin_phone","Telefon")}</>:<>{f("amount","Summa","number")}{f("paid_at","To'lov sanasi","date")}{f("period_from","Qaysi sanadan","date")}{f("period_to","Qaysi sanagacha","date")}{f("note","Izoh")}</>}</Box></DialogContent><DialogActions><Button onClick={close}>Bekor qilish</Button><Button variant="contained" onClick={save} disabled={saving}>{saving?"Saqlanmoqda...":"Saqlash"}</Button></DialogActions></Dialog>};
export default PlatformDashboard;
